#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DATABASE_USER WITH PASSWORD '$DATABASE_PASSWORD';

    CREATE DATABASE $DATABASE_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USER;

    CREATE DATABASE test_$DATABASE_NAME;
    GRANT ALL PRIVILEGES ON DATABASE test_$DATABASE_NAME TO $DATABASE_USER;
    COMMIT;
EOSQL

